### ISSUE TITLE
Описание проекта или списка

### ISSUE THREAD

**Issue by ASPIRE-AGENCY** [1312inc/pl2webasyst#21]
Добрый день, нам мы пользуемся вашим приложением у нас в бекенде, и нам очень не хватает полей Описаний у проекта или списка, для хранения информации.
Приходится пользоваться 2умя отдельными задачниками) Очень просим сделать данное поле 
<img width="1281" alt="Снимок экрана 2020-03-23 в 15 04 53" src="https://user-images.githubusercontent.com/13065503/77315087-f9bfe680-6d17-11ea-8b8d-9e06e6393e46.png">
<img width="1327" alt="Снимок экрана 2020-03-23 в 15 05 08" src="https://user-images.githubusercontent.com/13065503/77315096-fcbad700-6d17-11ea-9590-fd5dc4b77cd9.png">

**Comment by vofka** [comment]
Спасибо за пожелание! Поставил +1 в приоритете этой новой фичи. Мы планируем ее добавить в будущих релизах Pocket Lists, но пока не могу сказать о сроке ввода такой функции. Вероятнее всего, после интеграции с CRM и "Задачами" и последующего внедрения REST API. В iOS-приложении Pocket Lists описание для списков поддерживается, поэтому в любом случае в API такое поле будет. Тогда же постараемся добавить его и для проектов.
